FROM arm32v7/swipl:8.2.2

# Copiar archivos del proyecto al contenedor
COPY pengines_server /pengines_server

# Establecer el directorio de trabajo
WORKDIR /pengines_server

# Ejecutar el servidor de Prolog
ENTRYPOINT ["swipl", "run.pl"]

