name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-prolog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push 2248 Prolog server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-prolog
          platforms: linux/arm/v7
          push: true
          tags: matichewer/2248-dyj-prolog:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint
        run: curl -u ${{secrets.RASPI_USERNAME}}:${{secrets.RASPI_PASS}} https://chewer.ddns.net/hooks/deploy-2248-dyj
      
#  deploy:
#    needs: 
#      - build-and-push-prolog
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send webhook to Raspberry
#        uses: wei/curl@v1.1.1
#        with:
#          args: -u ${{secrets.RASPI_USERNAME}}:${{secrets.RASPI_PASS}} https://chewer.ddns.net/hooks/deploy-2248-dyj


