name: Test-webhook

on:
  push:
    branches:
      - develop

jobs:
  call_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Call Chewer endpoint
      run: curl -u ${{secrets.RASPI_USERNAME}}:${{secrets.RASPI_PASS}} https://chewer.ddns.net/hooks/test
